name: "Update Mozilla CA sub module"
on:
  workflow_dispatch:
    branches:
      - $default-branch

jobs:
  update_ca_module:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: "${{ github.event.inputs.btcgreen_ref }}"
          repository: btcgreen-network/btcgreen-blockchain
          submodules: recursive
          token: "${{ secrets.GITHUB_TOKEN }}"

      - name: Set up commit signing
        uses: BTCgreen-Network/actions/commit-sign/gpg@main
        with:
          gpg_private_key: ${{ secrets.BTCGREEN_AUTOMATION_PRIVATE_GPG_KEY }}
          passphrase: ${{ secrets.BTCGREEN_AUTOMATION_PRIVATE_GPG_PASSPHRASE }}

      - name: "Add changes to new branch"
        run: |
          cd ./mozilla-ca
          git pull origin main

      - name: "Create Pull Request"
        uses: peter-evans/create-pull-request@v4
        with:
          base: main
          body: "Newest Mozilla CA cert"
          branch: mozilla-ca-updates
          commit-message: "adding ca updates"
          delete-branch: true
          reviewers: "wjblanke,emlowe"
          assignees: "wallentx"
          title: "CA Cert updates"
          token: "${{ secrets.GITHUB_TOKEN }}"
          committer: "BTCgreenAutomation <automation@btcgreen.net>"
          author: "BTCgreenAutomation <automation@btcgreen.net>"
